### ISSUE TITLE
Doesn't work on (custom) "sugarss" document type

### ISSUE THREAD

**Issue by jrajav** [shinnn/vscode-stylelint#108]
Installing this together with https://marketplace.visualstudio.com/items?itemName=mhmadhamster.postcss-language works to validate "postcss" document type using this configuration:

```json
  "postcss.validate": false,
  "stylelint.enable": true,
  "stylelint.additionalDocumentSelectors": [
    "postcss"
  ],
```

However an equivalent configuration for SugarSS, included with that same plugin, does not work when the document type for the document is set to SugarSS (code "sugarss"):

```json
  "stylelint.enable": true,
  "stylelint.additionalDocumentSelectors": [
    "sugarss"
  ],
```

Stylelint is simply never run for SugarSS.

**Comment by shinnn** [comment]
I added `sugarss` to the list of default supported IDs https://github.com/shinnn/vscode-stylelint/commit/796b4a6c180383572a02f81172b4973667401ce3. Since [0.29.1](https://github.com/shinnn/vscode-stylelint/commit/cfe58b0e2f257493a163d9973832eff1de0b2d75), you don't even need to use `additionalDocumentSelectors` option.

Thanks for letting me know `vscode-postcss-language`. Seems really nice extension.
