### ISSUE TITLE
Add support for SASS

### ISSUE THREAD

**Issue by pzavolinsky** [shinnn/vscode-stylelint#128]
For example:

`style.sass`
```sass
.some-rule
  color: red
```

In other words, if `languageId` is `sass` set the `options.customSyntax = 'postcss-sass'` [here](https://github.com/shinnn/vscode-stylelint/blob/master/server.js#L33).

And, of course, listen for changes in `sass` files.

**Comment by shinnn** [comment]
Request built-in Sass support on [the issue tracker of the upstream stylelint project](https://github.com/stylelint/stylelint/issues). I assume it's reasonable since [`postcss-sass` is already included in the stylelint dependencies](https://github.com/stylelint/stylelint/commit/abe53c01878e28670540586b27bf001c7316c3fd).

If stylelint support Sass by default, I'll consider adding it to this project too.

**Comment by Grawl** [comment]
maybe you add custom syntaxes support, like Stylelint do?

**Comment by Grawl** [comment]
look, I created a repository to test how it's working and it's working correctly for now. https://github.com/Grawl/stylelint-sass-test

so we already can use it

**Comment by Grawl** [comment]
sorry for my english

**Comment by shinnn** [comment]
Now vscode-stylelint supports Sass by default. https://github.com/shinnn/vscode-stylelint/commit/c554d7afa6e2f3af7bb4dd5b09d14206ced72883
