### ISSUE TITLE
Friendly question: Why is autofix implementation blocked?

### ISSUE THREAD

**Issue by lydell** [shinnn/vscode-stylelint#270]
Hi! This is just a friendly question – I hope it’s ok!

I saw in https://github.com/shinnn/vscode-stylelint/issues/138#issuecomment-371955739 that autofix in this plugin is blocked on a bunch of stylelint issues. (The other thread is locked, so I cannot comment there.)

I recently switched over from Atom to VSCode. Atom’s [linter-stylelint](https://github.com/AtomLinter/linter-stylelint/) has autofix support. It has worked very well for me in .css and .scss files.

So … coming from Atom I’m wondering why autofix support is _blocked_ on those issues? Since it seemed to work so well in Atom, would it be possible to implement at least partial autofix support?

(Luckily, also using [Prettier](http://prettier.io/) reduces the need for autofix.)

Thanks for reading and for maintaining the plugin! :tada:

**Comment by shinnn** [comment]
Yes, I regard the bugs listed in https://github.com/shinnn/vscode-stylelint/issues/138#issuecomment-371955739 as *blockers*, because not all users are experts as you are.

Let me explain more details.

When stylelint started to support CSS-in-JS, I enabled it in this extension accordingly. But, unfortunately the initial implementation of CSS-in-JS support in stylelint had countless bugs and some of them are still not fixed today. Once this happens, the users submitted lots of issues about CSS-in-JS not to https://github.com/stylelint/stylelint/issues but *here*. All of them — not "most", actually "all" — blamed me, harassed me, had no investigation by themselves. Most of them are duplicated. The users didn't read even one issue closed right before.

I am sure that a user-made disaster happens again in just the same way if I add the autofixing feature to this extension. If they can differentiate stylelint bugs from vscode-stylelint bugs, write detailed bug reports, avoid opening duplicated issues and communicate respectfully, I'll happily implement autofix. However, I'm sorry to say, they never do.

That's the reason why I'm waiting for those bugs to be fixed.

**Comment by lydell** [comment]
I see, thanks for the answer! I am also sad to hear that you had such a bad time with users for the old implementation.

**Comment by griest024** [comment]
That's a real bummer that entitled idiots would ruin it for the rest of us who are just trying to get some work done...but so be it. Please reconsider your position on the autofix on save feature, it's been so helpful with eslint.
