### ISSUE TITLE
Add option to override stylelint path

### ISSUE THREAD

**Issue by larrifax** [shinnn/vscode-stylelint#4]
It would have been nice if we could override the path to stylelint, so that we can use our own version of stylelint. This way users could upgrade to new versions without having to wait for you to release a new version of your plugin.

**Comment by madcampos** [comment]
One option is to have it behave like eslint extension: users have to have it installed globally.

**Comment by thomas-darling** [comment]
Ideally I think it should just use whichever version is installed in the current repository - requireing a global install is definitely not ideal :-)

**Comment by skosno** [comment]
+1 for using current repository version with fallback to global npm installed module (I believe this is how eslint is configured as well). This way you can easily work with multiple projects using stylelint in different versions

**Comment by mrmlnc** [comment]
Related to: https://github.com/shinnn/stylelint-vscode/issues/2

**Comment by ivancuric** [comment]
And there it goes again. This is imho a top priority.

**Comment by kumarharsh** [comment]
@shinnn I really require a way to specify the stylelint path, and because my project depends on stylelint, and ideally I'd like to run stylelint in a pre-commit hook, similar to eslint. This would mean that my project would depend on stylelint. If my project depends on a stylelint version different than the one bundled with your plugin, it *might* cause problems where what I see in my text editor might not always be what I get in the pre-commit hook results, for example if stylelint fixes a bug or some API changes, etc.

Your plugin cannot maintain X number of stylelint versions, so it is fair to give the developers control over the stylelint version *they* want to install. But seeing as [you're against](https://github.com/shinnn/stylelint-vscode/issues/2#issuecomment-236482684) relying on developer specified stylelint module, I have a suggestion in that regard: bundle styleline in this plugin, but let the developer override it explicitly via a setting, similar to vscode-eslint's nodePath property. It's a win-win situation in that case.

**Comment by MindRave** [comment]
Hello! Any news on this? Stylelint 8.0.0 isn't cutting it on our project (rendering your extension, and thus, VSCode unusable) and we need to keep it to 7.9.0. It's either that or going back to Atom. 😞

**Comment by kumarharsh** [comment]
I can submit a PR if @shinnn would accept it.

**Comment by MindRave** [comment]
@kumarharsh that would be great! 😄 Let's see what @shinnn says.

**Comment by shinnn** [comment]
No thanks. Users of this extension don't know what stylelint is and how it works, still less how to install it. This feature probably bloats the issue tracker and I never spend my precious lifetime to close unproductive issues every time.
