### ISSUE TITLE
Start stylelint automatically as soon as a stylelint config is found

### ISSUE THREAD

**Issue by jp7677** [shinnn/vscode-stylelint#8]
Hello there,

I'm having a workspace in VS Code with several projects in it, see [https://github.com/jp7677/hellocoreclr](https://github.com/jp7677/hellocoreclr). Currently it is kind of work to get the VS Code stylelint extension to start linting. I need to enable the set the stylelint.enable property in the VS Code settings and I need to copy my stylelint.config.js from the Ui folder to the root folder. That way I end up with two stylelint configs, one for your extension and one for gulp. It would be nice if your extension would just immediately start after installing once a stylelint configuration is found somewhere in the solution.

Regards and keep up the good work.

**Comment by shinnn** [comment]
Add `stylelint.enable: true` to your user config (not workspace config) then it just works fine.

**Comment by shinnn** [comment]
https://github.com/shinnn/vscode-stylelint/issues/8#issue-148883552 includes two separate issues.

### (1) Enable this extension by default.

My first thought is https://github.com/shinnn/vscode-stylelint/issues/8#issuecomment-216086307. But, I didn't know the Microsoft official extensions are enabled by default. https://github.com/Microsoft/vscode-tslint/blob/69cf5a356eabd22e25100ecc7e8ae024bea4778e/tslint/package.json#L40 I'll change the default behavior in the next release. Thanks for creating [this commit](https://github.com/shinnn/vscode-stylelint/pull/9/commits/72df16414b7ff50b8b249484c64da3adddc026b3).

### (2) Stylelint doesn't find the config file automatically.

If config file lookup doesn't work as you expected, it should be reported on https://github.com/stylelint/stylelint/issues, instead of here.

**Comment by jp7677** [comment]
Hi,

Thanks for your response. Yes, these are indeed two issues. I didn't know that when creating the issue, though I figured that when coding too ;).

1) Thanks, If you don't mind I'll create a new issue for that so that it won't get lost.

2) When implementing my solution for this I mostly looked at the htmlhint code from Microsoft, [https://github.com/Microsoft/vscode-htmlhint/blob/master/htmlhint-server/src/server.ts](https://github.com/Microsoft/vscode-htmlhint/blob/master/htmlhint-server/src/server.ts). They do look for a .htmlhintrc in all directories between the workspace root directory and the location of the currently opened file. In my case it makes sense to do so since my VS Code workspace contains not just one but several projects [https://github.com/jp7677/hellocoreclr](https://github.com/jp7677/hellocoreclr). It looks more or less like:
```
/ <- workspace root
/Server <- some C# code
/Server.Test <- some C# code
/Ui <- the frontend web application
```
The `Ui` directory contains my gulpfile, typescript config, tslint settings and also my stylelint configuration. Since stylelint.config.js is not located in the workspace root but in a (project) directory below it is not possible for stylelint to know where my stylelint.config.js. Hence I think, and Microsoft thought so with htmlhint too, that we should give a hint about the location. What is your opinion on this?

**Comment by jp7677** [comment]
For 2) I have recreated my pull request including fixes for the points you commented on. See [https://github.com/shinnn/vscode-stylelint/pull/11](https://github.com/shinnn/vscode-stylelint/pull/11)

**Comment by shinnn** [comment]
> my pull request including fixes for the points you commented on.

You missed my comment. https://github.com/shinnn/vscode-stylelint/pull/9#issuecomment-216086316
